### ISSUE TITLE
Readme have some broken command

### ISSUE THREAD

**Issue by HydrolienF** [chirontt/lwjgl3-helloworld-native#2]
The executable is now in `build/native/nativeCompile/lwjgl3-helloworld` on Linux.

And maybe you should add `./` before every gradlew so that command line work on default Debian/Ubuntu terminal.

**Comment by chirontt** [comment]
Thanks for reporting some mistakes in the README file.

As to the `gradlew` or `mvnw` commands, they are intended to be generic, rather than catering for any specific platform (I'm not even sure if/how they work in MacOS!), so they should be applied appropriately to your specific OS (e.g. with a `./` prefix in Linux.)

**Comment by HydrolienF** [comment]
I understand.
It's ./ for Linux default shell, MacOS default shell and Windows with Powershell, so it's probably worth adding it to the command line as most of the users need it. But do as you like.
